parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     inomotorru
    database_user:     inomotorru
    database_password: eSh4Zai9ka

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            8d344465c1792f29c5a957315f22b526
